apiVersion: v1
kind: Service
metadata:
  name: {{ include "candid.fullname" . }}-frontend
  labels:
    {{- include "candid.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "candid.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
